spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transport
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
logging:
  level:
    sql: debug
    org:
      example: debug
  pattern:
    console: '%-5level - %msg%n'
